swagger: "2.0"
info:
  description: "An API for registering anonymous usage data events in CC Search, which we intend to use to improve the quality of the search results."
  version: "1.0.0"
  title: "CC Search Usage Data API"
  termsOfService: "https://api.openverse.engineering/terms_of_service.html"
  contact:
    email: "alden@creativecommons.org"
  license:
    name: "MIT License"
    url: "https://github.com/wordpress/openverse-api/blob/master/LICENSE"
host: "api.openverse.engineering"
basePath: "/analytics"
tags:
- name: "Register events"
  description: "Send events to the analytics server."
schemes:
- "https"
paths:
  /search_event:
    post:
      tags:
      - "Register events"
      summary: "Register a search query event."
      description: ""
      operationId: "addSearch"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "The user's search query and unique session UUID."
        required: true
        schema:
          $ref: "#/definitions/CreateSearchEvent"

      responses:
        400:
          description: "Invalid input"
  /search_rating_event:
    post:
      tags:
      - "Register events"
      summary: "Submit a user's rating of a search."
      description: ""
      operationId: "addSearchRating"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/CreateSearchRatingEvent"

      responses:
        201:
          description: "Created"
        400:
          description: "Invalid input"
  /result_click_event:
    post:
      tags:
      - "Register events"
      summary: "Submit an event indicating which result was clicked for a given search query."
      description: ""
      operationId: "addResultClick"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/CreateResultClickEvent"
      responses:
        201:
          description: "Created"
        400:
          description: "Invalid input"
  /detail_page_event:
    post:
      tags:
      - "Register events"
      summary: "Record events occurring on detail pages, such as sharing an image to social media or clicking through to its source."
      description: ""
      operationId: "addDetailPageEvent"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/CreateDetailPageEvent"
      responses:
        201:
          description: "Created"
        400:
          description: "Invalid input"

definitions:
  CreateSearchEvent:
    type: "object"
    required:
      - query
      - session_uuid
    properties:
      query:
        type: "string"
      session_uuid:
        type: "string"
        example: "12345678-1234-1234-1234-1234567890ab"

  CreateSearchRatingEvent:
    type: "object"
    required:
      - query
      - relevant
    properties:
      query:
        type: "string"
        description: "A unique identifier labeling an anonymous user's session."
      relevant:
        type: "boolean"
        example: true

  CreateResultClickEvent:
    type: "object"
    required:
      - query
      - session_uuid
      - result_uuid
      - result_rank
    properties:
      query:
        type: "string"
      result_rank:
        type: "integer"
        example: 2
        description: "The position of the result in the search results grid, e.g. 0 for the first result, or 22 for the 21st result."
      result_uuid:
        type: "string"
        example: "12345678-1234-1234-1234-1234567890ab"
        description: "The unique identifier for the result that was clicked."
      session_uuid:
        type: "string"
        example: "12345678-1234-1234-1234-1234567890ab"
        description: "A unique identifier labeling an anonymous user's session."

  CreateDetailPageEvent:
    type: "object"
    required:
      - event_type
      - result_uuid
    properties:
      event_type:
        type: "string"
        description: >
          Supported event types:
           * `ATTRIBUTION_CLICKED` - The user generated an attribution string for this result.
           * `REUSE_SURVEY` - The user took a reuse survey.
           * `SOURCE_CLICKED` - The user visited the source page of the work.
           * `CREATOR_CLICKED` - The user visited the creator of the work's page.
           * `SHARED_SOCIAL` - The user shared a link to the work on social media.
        example: "ATTRIBUTION_CLICKED"
        enum:
          - ATTRIBUTION_CLICKED
          - REUSE_SURVEY
          - SOURCE_CLICKED
          - CREATOR_CLICKED
          - SHARED_SOCIAL
      result_uuid:
        type: "string"
        example: "12345678-1234-1234-1234-1234567890ab"
        description: "The unique identifier for the detail page associated with the event."

externalDocs:
  description: "The Creative Commons search API"
  url: "https://api.openverse.engineering"
