#################################
# Dependabot Configuration File #
#################################

# current Github-native version of Dependabot 
version: 2

updates:
  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `/openverse-api` directory
    directory: '/openverse-api'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
      
  # Enable version updates for Python
  - package-ecosystem: 'pip'
    # Look for a `Pipfile` in the `/openverse-api` directory
    directory: '/openverse-api'
    # Check for updates once a week
    schedule:
      interval: 'weekly'
      
