#################################
# Dependabot Configuration File #
#################################

# current Github-native version of Dependabot
version: 2

updates:
  # Enable version updates for Python libs in Openverse API
  - package-ecosystem: pip
    # Look for a `Pipfile` in the `/api` directory
    directory: /api
    # Check for updates once a month
    schedule:
      interval: monthly
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ tech: python"
      - "ğŸ§± stack: api"
      - dependencies

  # Enable version updates for Python libs in ingestion server
  - package-ecosystem: pip
    # Look for a `Pipfile` in the `/ingestion_server` directory
    directory: /ingestion_server
    # Check for updates once a month
    schedule:
      interval: monthly
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ tech: python"
      - "ğŸ§± stack: ingestion server"
      - dependencies

  # Enable version updates for Python dev-libs in the catalog
  #
  # `requirements-dev.txt` can be updated more frequently than
  # `requirements_prod.txt` since they are not pinned by the Airflow constraints
  # file.
  - package-ecosystem: pip
    # Look for requirements file in the `/ingestion_server` directory
    directory: /catalog
    # Check for updates once a month
    schedule:
      interval: monthly
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ tech: python"
      - "ğŸ§± stack: catalog"
      - dependencies

  # Enable version updates for Python libs in documentation
  - package-ecosystem: pip
    # Look for a `Pipfile` in the `/documentation` directory
    directory: /documentation
    # Check for updates once a month
    schedule:
      interval: monthly
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ tech: python"
      - "ğŸ§± stack: documentation"
      - dependencies

  # Enable version updates for Python libs in automations/python
  - package-ecosystem: pip
    # Look for a `Pipfile` in the `/automations/python` directory
    directory: /automations/python
    # Check for updates once a month
    schedule:
      interval: monthly
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ tech: python"
      - "ğŸ§± stack: mgmt"
      - dependencies

  # Enable version updates in github-actions
  - package-ecosystem: "github-actions"
    directory: /actions/build-docs
    schedule:
      interval: "monthly"
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ§± stack: mgmt"
      - dependencies

  - package-ecosystem: "github-actions"
    directory: /actions/get-changes
    schedule:
      interval: "monthly"
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ§± stack: mgmt"
      - dependencies

  - package-ecosystem: "github-actions"
    directory: /actions/load-img
    schedule:
      interval: "monthly"
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ§± stack: mgmt"
      - dependencies

  - package-ecosystem: "github-actions"
    directory: /actions/setup-env
    schedule:
      interval: "monthly"
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ§± stack: mgmt"
      - dependencies
