#################################
# Dependabot Configuration File #
#################################

# current Github-native version of Dependabot
version: 2

updates:
  # Enable version updates for Python libs in Openverse API
  - package-ecosystem: pip
    # Look for a `Pipfile` in the `/api` directory
    directory: /api
    # Check for updates once a month
    schedule:
      interval: monthly
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ tech: python"
      - dependencies

  # Enable version updates for Python libs in ingestion server
  - package-ecosystem: pip
    # Look for a `Pipfile` in the `/ingestion_server` directory
    directory: /ingestion_server
    # Check for updates once a month
    schedule:
      interval: monthly
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - "ğŸ tech: python"
      - dependencies

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "monthly"
    labels:
      - "ğŸ’» aspect: code"
      - "ğŸ§° goal: internal improvement"
      - "ğŸŸ© priority: low"
      - dependencies
