[project]
name = "openverse-api-client"
version = "0.0.1"
description = "API client for Openverse"
authors = [
    {name = "Openverse Contributors", email = "openverse@wordpress.org"},
]
dependencies = [
    "httpx",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[tool.pdm.scripts]
pre_build = "pdm run generate"
test = { shell = "pytest" }
types = "mypy --install-types --non-interactive {args:src/openverse_api_client tests}"

generate = { call = "openverse_api_client_generator.__main__:cli" }
build_all = { shell = "pdm build && cd ../../js/api-client && pnpm run build" }

[tool.pdm.dev-dependencies]
dev = [
    "mypy>=1.10.0",
    "pyyaml>=6.0.1",
    "jinja2>=3.1.4",
    "pook>=1.4.3",
    "pytest>=8.2.2",
    "pytest-pook>=1.0.0",
    "pytest-asyncio>=0.23.7",
    "types-PyYAML>=6.0.12.20240311",
]

[tool.ruff.lint.per-file-ignores]
"_generated/*" = ["D200"]
