# This file is being synced from WordPress/openverse. Any changes made to it
# here will be overwritten. Please make any necessary edits to these files:
# - https://github.com/WordPress/openverse/blob/main/.pre-commit-config.yaml.jinja
# - https://github.com/WordPress/openverse/blob/main/templates/.pre-commit-config.local.yaml.jinja

exclude: Pipfile\.lock|migrations|\.idea|node_modules|archive

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: tsconfig.json # contains comments
      - id: check-case-conflict
      - id: check-toml
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: test/tapes/.+\.json5
      - id: check-symlinks
      - id: mixed-line-ending
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: check-docstring-first
      - id: requirements-txt-fixer

  # Use the `.isort.cfg` file to configure additional project-specific requirements.
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort
        files: \.py$
        exclude: ^build/.*$|^.tox/.*$|^venv/.*$
        args:
          - --profile=black
          - --lines-after-imports=2

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus

  # Use the `.flake8` file to configure additional project-specific requirements.
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --extend-ignore=E203,W503
          - --max-line-length=88

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --safe

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.2.2 # 6.2.3 is slightly broken
    hooks:
      - id: pydocstyle
        args:
          - --convention=pep257
          # Additional ignore reasons:
          # D1xx: we do not want to force contributors to write redundant or useless docstrings
          # D202: additional whitespace helps with readability
          # D211: same as D202
          # See the following documentation for what each rule does:
          # https://www.pydocstyle.org/en/6.2.3/error_codes.html#error-codes
          - --add-ignore=D1,D202,D211

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.15.0
    hooks:
      - id: eslint
        files: ^js/.*$
        "types": [file] # ESLint only accepts [javascript] by default.
        args:
          - --ignore-path=.gitignore
          - --ignore-path=.eslintignore
          - --max-warnings=0
        additional_dependencies:
          - eslint@8.15.0
          - eslint-config-prettier@8.5.0

  # Use the `.prettierignore` and `.prettier.config.js` files to configure project-specific requirements.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.6.0

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: render-precommit
        name: render-precommit
        entry: bash -c 'just render-precommit'
        language: system
        pass_filenames: false
      - id: render-prettier
        name: render-prettier
        entry: bash -c 'just render-prettier'
        language: system
        pass_filenames: false
      - id: render-github
        name: render-github
        entry: bash -c 'just render-github'
        language: system
        pass_filenames: false
