# This file is being synced from WordPress/openverse. Any changes made to it
# here will be overwritten. Please make any necessary edits to these files:
# - https://github.com/WordPress/openverse/blob/main/.pre-commit-config.yaml.jinja
# - https://github.com/WordPress/openverse/blob/main/.pre-commit-config.frontend.yaml.jinja

exclude: Pipfile\.lock|migrations|\.idea|node_modules|archive

repos:
  - repo: local # More local hooks are defined at the bottom.
    hooks:
      - id: i18n
        name: i18n
        # Check if the i18n files have been downloaded by checking if the Arabic translation exists
        # Download the i18n files if they do not exist
        entry: bash -c 'if [ ! -f "$(dirname "$dir")"/src/locales/ar.json ]; then pnpm i18n; fi'
        language: system
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: tsconfig.json # contains comments
      - id: check-case-conflict
      - id: check-toml
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: test/tapes/.+\.json5
      - id: check-symlinks
      - id: mixed-line-ending
      - id: fix-encoding-pragma
        args:
          - --remove

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.15.0
    hooks:
      - id: eslint
        files: \.(js|ts|vue)$
        exclude: ^nuxt-template-overrides/.*$ # ESLint raises warnings for ignored files.
        "types": [file] # ESLint only accepts [javascript] by default.
        args:
          - --ignore-path=.gitignore
          - --ignore-path=.eslintignore
          - --max-warnings=0
        additional_dependencies:
          - eslint@8.15.0
          - eslint-config-prettier@8.5.0
          - "@babel/eslint-parser@7.17.0"
          - "@intlify/eslint-plugin-vue-i18n@1.4.0"
          - "@nuxtjs/eslint-module@3.1.0"
          - "@typescript-eslint/eslint-plugin@5.23.0"
          - "@typescript-eslint/parser@5.23.0"
          - eslint-import-resolver-custom-alias@1.3.0
          - eslint-plugin-eslint-comments@3.2.0
          - eslint-plugin-import@2.26.0
          - eslint-plugin-prettier@4.0.0
          - eslint-plugin-tsdoc@0.2.16
          - eslint-plugin-unicorn@42.0.0
          - eslint-plugin-vue@9.4.0
          - eslint-plugin-vuejs-accessibility@1.1.1

  # Use the `.prettierignore` and `.prettier.config.js` files to configure project-specific requirements.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.6.0
          - prettier-plugin-tailwindcss@0.1.12
          - typescript@4.6.2

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.8.0
    hooks:
      - id: shellcheck

  - repo: local # More local hooks are defined at the top.
    hooks:
      - id: types
        name: types
        entry: bash -c 'pnpm types'
        language: system
        pass_filenames: false

      - id: test:unit
        name: test:unit
        entry: bash -c 'pnpm test:unit'
        language: system
        pass_filenames: false
        stages:
          - push
