language: python
addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-client-10
      - libexempi3
env:
  - CCCAPI_CONTAINER_NAME=cccatalog-api_web_1 ANALYTICS_CONTAINER_NAME=cccatalog-api_analytics_1
python:
- '3.7'
services:
  - docker
install:
  - pip3 install pipenv
  - cd cccatalog-api && pipenv install --system --deploy --dev && cd ..
  - cd ingestion_server && pipenv install --system --deploy --dev && cd ..
  - cd image_get/worker && pipenv install --system --deploy && cd ../../
  - cd analytics && pipenv install && cd ..
before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  - docker-compose up -d
  - bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8000/healthcheck)" != "200" ]]; do sleep 10; done'
  - ./load_sample_data.sh
  - bash -c 'while [[ "$(curl --insecure -s -o /dev/null -w ''%{http_code}'' http://localhost:8000/v1/images?q=test)" != "200" ]]; do sleep 5; done'
script:
  - pycodestyle cccatalog-api/cccatalog --exclude='cccatalog-api/cccatalog/api/migrations' --max-line-length=80 --ignore=E402,E702
  - pycodestyle ingestion_server/ingestion_server --max-line-length=80 --ignore=E402
  - cd cccatalog-api && test/run_test.sh
  - docker logs cccatalog-api_web_1
  - cd ../ingestion_server && pytest test/unit_tests.py
  - cd ../image_get/worker && pipenv run pytest
  - cd ../../ && docker logs cccatalog-api_web_1
  - cd ./analytics && API_URL='analytics:8090' pytest tests.py --disable-pytest-warnings
  - cd ../ && docker-compose logs analytics
