name: Compressed Size

on:
  pull_request:
    paths:
      - "**.ts"
      - "**.js"
      - "**.vue"
      - "**.css"
      # Changes to any dependency
      - "pnpm-lock.yaml"
      # This file configures ESLint. Changes could affect the outcome.
      - "**.eslint*"
      # This file configures Prettier. Changes could affect the outcome.
      - "**.prettier*"
      # This file configures TypeScript. Changes could affect the outcome.
      - "**.tsconfig*"
      # This file configures Nuxt (and therefore the build). Changes could affect the outcome.
      - "nuxt.config.ts"
      # This file configures Tailwind and could affect the style outcome.
      - "tailwind.config.js"
      # Changes to this workflow file should always verify the changes are successful.
      - ".github/workflows/bundle_size.yml"

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    if: github.repository == 'WordPress/openverse-frontend'

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - uses: preactjs/compressed-size-action@2.5.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          # Only measure changes in the client, we don't care much about the size of the server bundles (I don't think?)
          pattern: "./.nuxt/dist/client/**/*.{modern.js,js,css}"
