name: Nuxt bundle size

on:
  pull_request:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  get-changes:
    name: Get changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      frontend: ${{ steps.paths-filter.outputs.frontend }}
      lint: ${{ steps.paths-filter.outputs.lint }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changes
        id: paths-filter
        uses: ./.github/actions/get-changes

  build:
    name: Check
    runs-on: ubuntu-latest
    if: |
      github.repository == 'WordPress/openverse' &&
      (needs.get-changes.outputs.frontend == 'true' || needs.get-changes.outputs.lint == 'true')
    needs:
      - get-changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup CI env
        uses: ./.github/actions/setup-env
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          setup_python: false
          install_recipe: node-install

      - uses: preactjs/compressed-size-action@2.5.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Only measure changes in the client, we don't care much about the size of the server bundles (I don't think?)
          pattern: "./frontend/.nuxt/dist/client/**/*.{modern.js,js,css}"
          exclude: "{./frontend/.nuxt/dist/client/lang-*.json.js,./frontend/.nuxt/dist/client/lang-*.json.modern.js}"
          minimum-change-threshold: 10

      - name: Checkout repository # again, to enable cleaning
        if: always()
        uses: actions/checkout@v3
