name: CI

on:
  push:
    branches: -main
  pull_request:

jobs:
  types:
    name: Check types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Check types
        run: pnpm types

  lint:
    name: Lint files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Lint with ESLint and Prettier
        run: pnpm lint

  i18n:
    name: Check translation files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Check extracted strings
        run: pnpm i18n:check

      - name: Check POT files are updated
        shell: bash
        run: pnpm i18n:generate-pot

  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run unit tests
        run: pnpm test:unit

  playwright:
    name: Playwright tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run playwright tests
        run: pnpm test:playwright

      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: test-results
          path: test-results

  storybook:
    name: Check Storybook build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run Storybook smoke-test
        run: pnpm storybook:smoke

  build:
    name: Check Nuxt build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run build
        run: pnpm build
