name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  types:
    name: Check types
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Check types
        run: pnpm types

  lint:
    name: Lint files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Lint with ESLint and Prettier
        run: pnpm lint

  i18n:
    name: Check translation files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Check extracted strings
        run: pnpm i18n:check

      - name: Check POT files are updated
        shell: bash
        run: pnpm i18n:generate-pot

  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run unit tests
        run: pnpm test:unit

  clean-playwright-failure-comment:
    name: Remove previous Playwright test failure comments
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - uses: peter-evans/find-comment@v2
        id: test-results-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Playwright Failure Test Results

      - uses: actions/github-script@v6
        if: steps.test-results-comment.outputs.comment-id != 0
        with:
          script: |
            await github.rest.issues.deleteComment({
              repo: context.repo.repo,
              owner: context.repo.owner,
              comment_id: ${{ steps.test-results-comment.outputs.comment-id }}
            })
            console.log('Deleted comment with ID ${{ steps.test-results-comment.outputs.comment-id }}')

  nuxt-playwright:
    name: Nuxt Playwright tests
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run Nuxt Playwright tests
        run: pnpm test:playwright

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: nuxt-test-results
          path: test-results

  storybook-playwright:
    name: Storybook Playwright tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run Storybook Playwright tests
        run: pnpm test:storybook

      - uses: actions/upload-artifact@v3
        if: failure()
        id: test-results
        with:
          name: storybook-test-results
          path: test-results

  playwright-test-failure-comment:
    name: Share Playwright test debugging instructions
    runs-on: ubuntu-latest
    if: always() && github.ref != 'refs/heads/main' && (needs.nuxt-playwright.result == 'failure' || needs.storybook-playwright.result == 'failure')
    needs:
      - nuxt-playwright
      - storybook-playwright

    steps:
      - uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Playwright Failure Test Results**

            It looks like some of the Playwright tests failed. You can download the Playwright trace
            output for both Storybook and Nuxt Playwright tests that have failed at the bottom of this
            page, under the "Artifacts" section:

            <https://github.com/WordPress/openverse-frontend/actions/runs/${{ github.run_id }}>

            Read more about how to use this artifact here: <https://github.com/WordPress/openverse-frontend/blob/main/test/playwright/README.md#debugging>

  storybook:
    name: Check Storybook build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run Storybook smoke-test
        run: pnpm storybook:smoke

  build:
    name: Check Nuxt build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Run build
        run: pnpm build

  gh-pages:
    name: PR Storybook and Tailwind Preview
    if: github.repository == 'WordPress/openverse-frontend' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: peter-evans/find-comment@v2
        id: preview-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Storybook and Tailwind configuration previews

      - uses: peter-evans/create-or-update-comment@v2
        if: steps.preview-comment.outputs.comment-id != 0
        with:
          comment-id: ${{ steps.preview-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            **Storybook and Tailwind configuration previews**: _Updating_
            (This comment will be automatically updated with the preview URLs once they are ready)

      - uses: peter-evans/create-or-update-comment@v2
        if: steps.preview-comment.outputs.comment-id == 0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Storybook and Tailwind configuration previews**: _Updating_
            (This comment will be automatically updated with the preview URLs once they are ready)

      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup-node-env

      - name: Fetch translation files
        run: pnpm i18n

      - name: Build Storybook
        run: pnpm storybook:build

      - name: Build Tailwind Config Viewer
        run: pnpm tcv:build

      # This makes the TCV available at the `/tailwind` directory in the gh-pages
      - name: Merge TCV and Storybook builds
        run: mv .tcv-export ./storybook-static/tailwind

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          destination_dir: ${{ github.event.pull_request.number }}
          keep_files: true

      - uses: peter-evans/find-comment@v2
        id: final-preview-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Storybook and Tailwind configuration previews

      - uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.final-preview-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            **Storybook and Tailwind configuration previews**: _Ready_

            **Storybook:** <https://wordpress.github.io/openverse-frontend/${{ github.event.pull_request.number }}>
            **Tailwind:** <https://wordpress.github.io/openverse-frontend/${{ github.event.pull_request.number }}/tailwind>

            Please note that GitHub pages takes a little time to deploy newly pushed code, if the links above don't work or you see old versions, wait 5 minutes and try again.

            You can check [the GitHub pages deployment action list](https://github.com/WordPress/openverse-frontend/actions/workflows/pages/pages-build-deployment) to see the current status of the deployments.
