# name: cccatalog-frontend-ci

# on:
#   push:
#     branches:
#       - master
#       - develop
#   pull_request:
#     branches:
#       - develop

# jobs:
#   ci:
#     name: Run CI tests
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v1
#         with:
#           node-version: '12.4.0'

#       - name: Cache Node.js modules
#         uses: actions/cache@v1
#         with:
#           path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
#           key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
#           restore-keys: |
#             ${{ runner.OS }}-node-
#             ${{ runner.OS }}-

#       - name: Install dependencies
#         run: npm ci

#       - name: Run lint
#         run: npm run lint

#       - name: Run formatting test
#         run: npm run format:test

#       - name: Run tests
#         run: npm run test:unit

#       - name: Run build
#         run: npm run build
