name: Label sync
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#label-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # at 00:00

env:
  LOGGING_LEVEL: 20 # corresponds to INFO
  ACCESS_TOKEN: ${{ github.token }}

jobs:
  sync_labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: ./python
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user pipenv
          pipenv install --deploy

      - name: Sync standard labels
        working-directory: ./python
        run: |
          pipenv run python sync_labels.py
