name: New issue automation
# â„¹ï¸ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#new-issue-automation

on:
  issues:
    types:
      - opened
env:
  GH_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Projects need a personal access token to work.
  ISSUE_ID: ${{ github.event.issue.node_id }} # The global issue ID that works in both REST and GraphQL APIs.

jobs:
  add_issue:
    name: Add new issue
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to "Backlog"
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Openverse
          column: Backlog
          # TODO: Switch to GITHUB_TOKEN if the project is moved to a repo
          repo-token: ${{ secrets.ACCESS_TOKEN }}

  add_issue_to_project:
    name: Add new issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: bulatt3/add-to-project-and-label@v0.0.2
        with:
          project-url: https://github.com/orgs/WordPress/projects/75
          github-token: ${{ secrets.ACCESS_TOKEN }}
          # Exclude the issues with the following labels
          labeled: project
          label-operator: NOT
          label-map: |
            { "Priority": [
              { "label": "ğŸŸ¥ priority: critical", "fieldValue": "ğŸŸ¥ priority: critical" },
              { "label": "ğŸŸ§ priority: high", "fieldValue": "ğŸŸ§ priority: high" },
              { "label": "ğŸŸ¨ priority: medium", "fieldValue": "ğŸŸ¨ priority: medium" },
              { "label": "ğŸŸ© priority: low", "fieldValue": "ğŸŸ© priority: low" }
            ]}
