name: New PR automation
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#new-pr-automation

on:
  pull_request:
    types:
    - opened
    - converted_to_draft
    - ready_for_review

jobs:
  add_draft:
    name: Add draft PR
    if: ${{ github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
    - name: Add PR to "In progress"
      uses: alex-page/github-project-automation-plus@v0.8.1
      with:
        project: Openverse
        column: In progress
        repo-token: ${{ secrets.ACCESS_TOKEN }}

  add_ready:
    name: Add ready PR
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
    - name: Add PR to "Needs review"
      uses: alex-page/github-project-automation-plus@v0.8.1
      with:
        project: Openverse
        column: Needs review
        repo-token: ${{ secrets.ACCESS_TOKEN }}
