name: PR label check
# â„¹ï¸ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#pr-label-check

on:
  pull_request:
    types:
      # Default types
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
      - opened
      - reopened
      - synchronize
      # Label is changed
      - labeled
      - unlabeled

jobs:
  # List of aspect labels: https://github.com/WordPress/openverse/labels?q=aspect
  check_aspect_label:
    name: Check aspect label
    runs-on: ubuntu-latest
    steps:
      - name: Check aspect label
        uses: docker://agilepathway/pull-request-label-checker:v1.2.13
        with:
          one_of: "ğŸ’» aspect: code,ğŸ“„ aspect: text,ğŸ¤– aspect: dx,ğŸ•¹ aspect: interface,â™¿ï¸ aspect: a11y"
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  # List of goal labels: https://github.com/WordPress/openverse/labels?q=goal
  check_goal_label:
    name: Check goal label
    runs-on: ubuntu-latest
    steps:
      - name: Check goal label
        uses: docker://agilepathway/pull-request-label-checker:v1.2.13
        with:
          one_of: "ğŸŒŸ goal: addition,ğŸ›  goal: fix,âœ¨ goal: improvement,ğŸ§° goal: internal improvement"
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  # List of priority labels: https://github.com/WordPress/openverse/labels?q=priority
  check_priority_label:
    name: Check priority label
    runs-on: ubuntu-latest
    steps:
      - name: Check priority label
        uses: docker://agilepathway/pull-request-label-checker:v1.2.13
        with:
          one_of: "ğŸŸ© priority: low,ğŸŸ¨ priority: medium,ğŸŸ§ priority: high,ğŸŸ¥ priority: critical"
          repo_token: ${{ secrets.GITHUB_TOKEN }}

  # List of stack labels: https://github.com/WordPress/openverse/labels?q=stack
  check_stack_label:
    name: Check stack label
    runs-on: ubuntu-latest
    steps:
      - name: Check stack label
        uses: docker://agilepathway/pull-request-label-checker:v1.2.13
        with:
          any_of: "ğŸ§± stack: backend,ğŸ§± stack: analytics, ğŸ§± stack: documentation,ğŸ§± stack: frontend,ğŸ§± stack: mgmt,ğŸ§± stack: api,ğŸ§± stack: catalog,ğŸ§± stack: ingestion server,ğŸ§± stack: infra"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
