name: PR label check
# â„¹ï¸ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#pr-label-check

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  check_aspect_label:
    name: Check aspect label
    runs-on: ubuntu-latest
    steps:
      - name: Check aspect label
        uses: sugarshin/required-labels-action@v0.3.2
        with:
          required_oneof: "ğŸš¦ status: awaiting triage,ğŸ’» aspect: code,ğŸ“„ aspect: text,ğŸ¤– aspect: dx,ğŸ•¹ aspect: interface,â™¿ï¸ aspect: a11y"

  check_goal_label:
    name: Check goal label
    runs-on: ubuntu-latest
    steps:
      - name: Check goal label
        uses: sugarshin/required-labels-action@v0.3.2
        with:
          required_oneof: "ğŸš¦ status: awaiting triage,ğŸŒŸ goal: addition,ğŸ›  goal: fix,âœ¨ goal: improvement,ğŸ§° goal: internal improvement"

  check_priority_label:
    name: Check priority label
    runs-on: ubuntu-latest
    steps:
      - name: Check priority label
        uses: sugarshin/required-labels-action@v0.3.2
        with:
          required_oneof: "ğŸš¦ status: awaiting triage,ğŸŸ© priority: low,ğŸŸ¨ priority: medium,ğŸŸ§ priority: high,ğŸŸ¥ priority: critical"
