name: PR label check
# â„¹ï¸ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#pr-label-check

on:
  pull_request:
    types:
    - opened
    - edited
    - labeled
    - unlabeled
    - synchronize

jobs:
  check_aspect_label:
    name: Check aspect label
    runs-on: ubuntu-latest
    steps:
    - name: Check aspect label
      uses: sugarshin/required-labels-action@v0.3.1
      with:
        required_oneof: 'ğŸ’» aspect: code,ğŸ“„ aspect: text,ğŸ¤– aspect: dx,ğŸ•¹ aspect: interface,â™¿ï¸ aspect: a11y'

  check_goal_label:
    name: Check goal label
    runs-on: ubuntu-latest
    steps:
    - name: Check goal label
      uses: sugarshin/required-labels-action@v0.3.1
      with:
        required_oneof: 'ğŸŒŸ goal: addition,ğŸ›  goal: fix,âœ¨ goal: improvement,ğŸ§° goal: internal improvement'
