name: PR label check
# â„¹ï¸ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#pr-label-check

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  set_label:
    name: Set labels
    runs-on: ubuntu-latest
    # Only set labels when the PR is created, this should fire `labeled` events
    # that will trigger the checks below.
    if: github.event.action == 'opened'
    steps:
      - name: Trigger remote workflow
        uses: felixp8/dispatch-and-wait@v0.1.0
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
        with:
          owner: WordPress
          repo: openverse
          token: ${{ secrets.ACCESS_TOKEN }}
          event_type: label_pr
          client_payload: ${{ format('{{"pr_url":"{0}"}}', env.PR_URL) }}
          wait_time: 5
          max_time: 60

  check_aspect_label:
    name: Check aspect label
    needs:
      - set_label
    # Check labels only when labels change
    if: github.event.action != 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Check aspect label
        uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: "ğŸš¦ status: awaiting triage,ğŸ’» aspect: code,ğŸ“„ aspect: text,ğŸ¤– aspect: dx,ğŸ•¹ aspect: interface,â™¿ï¸ aspect: a11y"

  check_goal_label:
    name: Check goal label
    needs:
      - set_label
    # Check labels only when labels change
    if: github.event.action != 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Check goal label
        uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: "ğŸš¦ status: awaiting triage,ğŸŒŸ goal: addition,ğŸ›  goal: fix,âœ¨ goal: improvement,ğŸ§° goal: internal improvement"

  check_priority_label:
    name: Check priority label
    needs:
      - set_label
    # Check labels only when labels change
    if: github.event.action != 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Check priority label
        uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: "ğŸš¦ status: awaiting triage,ğŸŸ© priority: low,ğŸŸ¨ priority: medium,ğŸŸ§ priority: high,ğŸŸ¥ priority: critical"
