name: Project automation
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#project-automation

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *" # every 15 minutes

env:
  LOGGING_LEVEL: 20 # corresponds to INFO
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Can't search in the private infra repo with GITHUB_TOKEN

jobs:
  move_issues:
    name: Move issues to "In Progress"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: ./automations/python
        run: |
          python -m pip install --user --upgrade pip
          python -m pip install --user pipenv
          pipenv install --deploy

      - name: Move issues from "To do"
        working-directory: ./automations/python
        run: |
          pipenv run python issues_with_prs.py \
          --project-number 3 \
          --source-column "To do" \
          --target-column "In progress" \ 
          --linked-pr-state "open"

      - name: Move issues from "Backlog"
        working-directory: ./automations/python
        run: |
          pipenv run python issues_with_prs.py \
          --project-number 3 \
          --source-column "Backlog" \
          --target-column "In progress" \
          --linked-pr-state "open"

      - name: Move stale issues from "In progress"
        working-directory: ./automations/python
        run: |
          pipenv run python issues_with_prs.py \
          --project-number 3 \
          --source-column "In progress" \
          --target-column "Backlog" \
          --linked-pr-state "closed"
