name: Publish Docker images on-demand
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to push (options: "api", "api_nginx", or "ingestion_server")'
        required: true
      commit:
        description: Commit that the image is built from
        required: true

concurrency: ${{ github.workflow }}-${{ inputs.image }}-${{ inputs.commit }}

jobs:
  push:
    name: Publish requested Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download image `${{ github.event.inputs.image }}`
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci_cd.yml
          workflow_conclusion: success
          commit: ${{ github.event.inputs.commit }}
          name: ${{ github.event.inputs.image }}
          path: /tmp

      - name: Load and tag image `${{ github.event.inputs.image }}`
        env:
          INPUT_IMAGE: ${{ github.event.inputs.image }}
        run: |
          docker load --input "/tmp/$INPUT_IMAGE.tar"
          docker tag "openverse-$INPUT_IMAGE" \
            "ghcr.io/wordpress/openverse-$INPUT_IMAGE:${{ github.event.inputs.commit }}"
          docker push --all-tags "ghcr.io/wordpress/openverse-$INPUT_IMAGE"
