name: Automated testing workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: |
          cd ./src/cc_catalog_airflow
          cp env.template .env
          docker-compose up -d
      - name: Test
        run: |
          sleep 10
          docker exec cc_catalog_airflow_webserver_1 /usr/local/airflow/.local/bin/pytest