name: Renovate
on:
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: "0/15 * * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    if: github.repository == 'WordPress/openverse'
    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v39.1.1
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.ACCESS_TOKEN }}
