name: Meta file sync
# ‚ÑπÔ∏è https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#meta-file-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - "automations/**"
      - ".github/**"

jobs:
  sync_meta:
    name: Sync meta files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run file sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.ACCESS_TOKEN }} # Can't use GITHUB_TOKEN to make PRs on other repos
          PR_LABELS: |
            üß∞ goal: internal improvement
            ü§ñ aspect: dx
            üüß priority: high
            üß± stack: mgmt
            skip-changelog
