name: Weekly updates
# ℹ️ https://github.com/WordPress/openverse/blob/main/.github/GITHUB.md#project-automation

on:
  workflow_dispatch:
  schedule:
    - cron: "1 0 * * 1" # just after midnight on Monday

env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  MAKE_USERNAME: ${{ secrets.MAKE_USERNAME }}
  MAKE_PASSWORD: ${{ secrets.MAKE_PASSWORD }} # application password, not login password

jobs:
  make_post:
    name: Create post on Make site
    runs-on: ubuntu-latest
    if: github.repository_owner == 'WordPress'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CI env
        uses: ./.github/actions/setup-env
        with:
          setup_python: false
          install_recipe: node-install

      - name: Publish post
        run: just automations/js/report
